version: '3'

services:

  #Parametros del Wordpress:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: ['./:/var/www/html'] #uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: Workadmin
        WORDPRESS_DB_PASSWORD: Password
    ports:
      - 8000:80 #Expose http
    networks:
      - wpsite

  #Parametros del MYSQL:
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: Workadmin
      MYSQL_PASSWORD: Password
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Password
    networks:
      - wpsite
    
networks:
  wpsite:
volumes:
  db_data: